# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'mobile-challenger' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'AFNetworking', '3.0'
  pod 'SDWebImage', '~> 5.0'
  pod 'UIScrollView-InfiniteScroll'
  pod 'Mantle'

  # Pods for mobile-challenger

  target 'mobile-challengerTests' do
    inherit! :search_paths
    pod 'Quick', '2.1.0'
    pod 'Nimble', '8.0.2'
    # Pods for testing
  end

  target 'mobile-challengerUITests' do
    # Pods for testing
  end

end
